FROM python:3.9-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY aws_requirements.txt /usr/src/app/

RUN pip3 install --no-cache-dir -r aws_requirements.txt

COPY aws_controller.py /usr/src/app/

ENTRYPOINT ["python3"]

CMD ["-m", "aws_controller.py"]
